---
- import_playbook: ../infrastructure/stretch-playbook.yml
- import_playbook: ../bind/bind-firewall-playbook.yml
- import_playbook: ../postfix/postfix-firewall-playbook.yml
- import_playbook: ../icinga/icinga-firewall-playbook.yml
- import_playbook: ../wazuh/wazuh-firewall-playbook.yml
- import_playbook: firewall-playbook.yml
